version: '3.7'

services:
  airbyte-server:
    image: airbyte/server:0.39.0-alpha
    container_name: airbyte-server
    environment:
      - AIRBYTE_ROLE=server
      - AIRBYTE_DB_HOST=airbyte-db
      - AIRBYTE_DB_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - airbyte-db
    networks:
      - airbyte-network

  airbyte-webapp:
    image: airbyte/webapp:0.39.0-alpha
    container_name: airbyte-webapp
    environment:
      - AIRBYTE_ROLE=webapp
      - AIRBYTE_API_URL=http://airbyte-server:8000/api
    ports:
      - "8001:80"
    depends_on:
      - airbyte-server
    networks:
      - airbyte-network

  airbyte-db:
    image: postgres:13
    container_name: airbyte-db
    environment:
      - POSTGRES_USER=airbyte
      - POSTGRES_PASSWORD=airbyte
      - POSTGRES_DB=airbyte
    volumes:
      - airbyte-db-data:/var/lib/postgresql/data
    networks:
      - airbyte-network

networks:
  airbyte-network:
    driver: bridge

volumes:
  airbyte-db-data:
    driver: local
